/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksTickerRouteImport } from './routes/stocks.$ticker'
import { Route as ApiStocksQuoteRouteImport } from './routes/api/stocks/quote'
import { Route as ApiStocksBoardRouteImport } from './routes/api/stocks/board'
import { Route as ApiPublicHooksSignalsRouteImport } from './routes/api/public/hooks/signals'
import { Route as ApiPublicHooksScrapeNewsRouteImport } from './routes/api/public/hooks/scrape-news'
import { Route as ApiPublicHooksComputeTrendsRouteImport } from './routes/api/public/hooks/compute-trends'
import { Route as ApiPublicHooksAnalyzeSentimentRouteImport } from './routes/api/public/hooks/analyze-sentiment'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksTickerRoute = StocksTickerRouteImport.update({
  id: '/stocks/$ticker',
  path: '/stocks/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksQuoteRoute = ApiStocksQuoteRouteImport.update({
  id: '/api/stocks/quote',
  path: '/api/stocks/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksBoardRoute = ApiStocksBoardRouteImport.update({
  id: '/api/stocks/board',
  path: '/api/stocks/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSignalsRoute = ApiPublicHooksSignalsRouteImport.update({
  id: '/api/public/hooks/signals',
  path: '/api/public/hooks/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeNewsRoute =
  ApiPublicHooksScrapeNewsRouteImport.update({
    id: '/api/public/hooks/scrape-news',
    path: '/api/public/hooks/scrape-news',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksComputeTrendsRoute =
  ApiPublicHooksComputeTrendsRouteImport.update({
    id: '/api/public/hooks/compute-trends',
    path: '/api/public/hooks/compute-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAnalyzeSentimentRoute =
  ApiPublicHooksAnalyzeSentimentRouteImport.update({
    id: '/api/public/hooks/analyze-sentiment',
    path: '/api/public/hooks/analyze-sentiment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/pulse': typeof PulseRoute
  '/terms': typeof TermsRoute
  '/watchlist': typeof WatchlistRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/api/stocks/board': typeof ApiStocksBoardRoute
  '/api/stocks/quote': typeof ApiStocksQuoteRoute
  '/api/public/hooks/analyze-sentiment': typeof ApiPublicHooksAnalyzeSentimentRoute
  '/api/public/hooks/compute-trends': typeof ApiPublicHooksComputeTrendsRoute
  '/api/public/hooks/scrape-news': typeof ApiPublicHooksScrapeNewsRoute
  '/api/public/hooks/signals': typeof ApiPublicHooksSignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/pulse': typeof PulseRoute
  '/terms': typeof TermsRoute
  '/watchlist': typeof WatchlistRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/api/stocks/board': typeof ApiStocksBoardRoute
  '/api/stocks/quote': typeof ApiStocksQuoteRoute
  '/api/public/hooks/analyze-sentiment': typeof ApiPublicHooksAnalyzeSentimentRoute
  '/api/public/hooks/compute-trends': typeof ApiPublicHooksComputeTrendsRoute
  '/api/public/hooks/scrape-news': typeof ApiPublicHooksScrapeNewsRoute
  '/api/public/hooks/signals': typeof ApiPublicHooksSignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/pulse': typeof PulseRoute
  '/terms': typeof TermsRoute
  '/watchlist': typeof WatchlistRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/api/stocks/board': typeof ApiStocksBoardRoute
  '/api/stocks/quote': typeof ApiStocksQuoteRoute
  '/api/public/hooks/analyze-sentiment': typeof ApiPublicHooksAnalyzeSentimentRoute
  '/api/public/hooks/compute-trends': typeof ApiPublicHooksComputeTrendsRoute
  '/api/public/hooks/scrape-news': typeof ApiPublicHooksScrapeNewsRoute
  '/api/public/hooks/signals': typeof ApiPublicHooksSignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/pulse'
    | '/terms'
    | '/watchlist'
    | '/stocks/$ticker'
    | '/api/stocks/board'
    | '/api/stocks/quote'
    | '/api/public/hooks/analyze-sentiment'
    | '/api/public/hooks/compute-trends'
    | '/api/public/hooks/scrape-news'
    | '/api/public/hooks/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/pulse'
    | '/terms'
    | '/watchlist'
    | '/stocks/$ticker'
    | '/api/stocks/board'
    | '/api/stocks/quote'
    | '/api/public/hooks/analyze-sentiment'
    | '/api/public/hooks/compute-trends'
    | '/api/public/hooks/scrape-news'
    | '/api/public/hooks/signals'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/pulse'
    | '/terms'
    | '/watchlist'
    | '/stocks/$ticker'
    | '/api/stocks/board'
    | '/api/stocks/quote'
    | '/api/public/hooks/analyze-sentiment'
    | '/api/public/hooks/compute-trends'
    | '/api/public/hooks/scrape-news'
    | '/api/public/hooks/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  PulseRoute: typeof PulseRoute
  TermsRoute: typeof TermsRoute
  WatchlistRoute: typeof WatchlistRoute
  StocksTickerRoute: typeof StocksTickerRoute
  ApiStocksBoardRoute: typeof ApiStocksBoardRoute
  ApiStocksQuoteRoute: typeof ApiStocksQuoteRoute
  ApiPublicHooksAnalyzeSentimentRoute: typeof ApiPublicHooksAnalyzeSentimentRoute
  ApiPublicHooksComputeTrendsRoute: typeof ApiPublicHooksComputeTrendsRoute
  ApiPublicHooksScrapeNewsRoute: typeof ApiPublicHooksScrapeNewsRoute
  ApiPublicHooksSignalsRoute: typeof ApiPublicHooksSignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$ticker': {
      id: '/stocks/$ticker'
      path: '/stocks/$ticker'
      fullPath: '/stocks/$ticker'
      preLoaderRoute: typeof StocksTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks/quote': {
      id: '/api/stocks/quote'
      path: '/api/stocks/quote'
      fullPath: '/api/stocks/quote'
      preLoaderRoute: typeof ApiStocksQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks/board': {
      id: '/api/stocks/board'
      path: '/api/stocks/board'
      fullPath: '/api/stocks/board'
      preLoaderRoute: typeof ApiStocksBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/signals': {
      id: '/api/public/hooks/signals'
      path: '/api/public/hooks/signals'
      fullPath: '/api/public/hooks/signals'
      preLoaderRoute: typeof ApiPublicHooksSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-news': {
      id: '/api/public/hooks/scrape-news'
      path: '/api/public/hooks/scrape-news'
      fullPath: '/api/public/hooks/scrape-news'
      preLoaderRoute: typeof ApiPublicHooksScrapeNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/compute-trends': {
      id: '/api/public/hooks/compute-trends'
      path: '/api/public/hooks/compute-trends'
      fullPath: '/api/public/hooks/compute-trends'
      preLoaderRoute: typeof ApiPublicHooksComputeTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/analyze-sentiment': {
      id: '/api/public/hooks/analyze-sentiment'
      path: '/api/public/hooks/analyze-sentiment'
      fullPath: '/api/public/hooks/analyze-sentiment'
      preLoaderRoute: typeof ApiPublicHooksAnalyzeSentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  PulseRoute: PulseRoute,
  TermsRoute: TermsRoute,
  WatchlistRoute: WatchlistRoute,
  StocksTickerRoute: StocksTickerRoute,
  ApiStocksBoardRoute: ApiStocksBoardRoute,
  ApiStocksQuoteRoute: ApiStocksQuoteRoute,
  ApiPublicHooksAnalyzeSentimentRoute: ApiPublicHooksAnalyzeSentimentRoute,
  ApiPublicHooksComputeTrendsRoute: ApiPublicHooksComputeTrendsRoute,
  ApiPublicHooksScrapeNewsRoute: ApiPublicHooksScrapeNewsRoute,
  ApiPublicHooksSignalsRoute: ApiPublicHooksSignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
